name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: ${{ matrix.name }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
          - os: macOS-latest
            name: macOS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install OSMesa
        run: |
          sudo apt update
          sudo wget https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb
          sudo dpkg -i ./mesa_18.3.3-0.deb || true
          sudo apt install -f
          
      - name: Install forked pyopengl
        run: |
          git clone https://github.com/mmatl/pyopengl.git
          pip install ./pyopengl

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install libigl
        run: |
          git clone https://github.com/libigl/libigl-python-bindings.git
          cd libigl-python-bindings
          python setup.py install

      - name: Test
        run: python render.py --help
